### ISSUE TITLE
Purchasable's options not saved in specify-option page

### ISSUE THREAD

**Issue by hintyu** [swsnu/swpp18-team11#9]
specify-order page에서 select-order component를 사용하지 않고 단품만 my cart에 넣는 경우 option이 null이 되면서 이후 my-cart page에서 option 가격이 NaN이 되는 현상이 발생.
select-order component를 사용했을 때는 option들이 제대로 저장되는 걸로 보아 specify-order page에 약간 문제가 있는 듯. 수정하겠습니다

**Comment by Algy** [comment]
Closed by #10
